# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# External plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

title: Unsanctioned Magic
subtitle: "As above, so below."
email: us@unsanctionedmagic.com
description: >- # this means to ignore newlines until "baseurl:"
  Bring your Magic into the real world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unsanctionedmagic.com" # the base hostname & protocol for your site, e.g. http://example.com
cover: "/assets/header_image_dark.jpg"
logo: "/assets/logo.svg"

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

# Disqus comments
# disqus_shortname: 

# Google analytics
# ga_tracking_id: ""

# Category descriptions (for archive pages)
descriptions:
  - cat: Swig-N'-Sealed
    
  - cat: Drafts-and-Draft
    desc: "Drafts and Draft posts."

  - cat: News
 
    
# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Facebook
    icon: facebook
    username: "unsanctionedmagic"
    url: https://www.facebook.com/unsanctionedmagic/
    desc: Like us on Facebook
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.svg"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/svg"

    twitter_image: "/assets/logo.svg"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
